--- 
- name: APT - Add elastic.co repository
  get_url: 
     url: "https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-oss-7.10.0-amd64.deb" 
     dest: /

- name: METRICBEAT - Install Metricbeat
  command: 
     dpkg -i /metricbeat-oss-7.10.0-amd64.deb

- name: METRICBEAT - Copy base metricbeat config file
  copy: 
     src: /home/vagrant/ansible/roles/wordpress/templates/metricbeat-conf.yml 
     dest: /etc/metricbeat/metricbeat.yml

- name: METRICBEAT - Enable nginx system
  command:
     metricbeat modules enable nginx system

- name: METRICBEAT - Set up assets
  command:
     metricbeat setup --pipelines --index-management --dashboards -c /etc/metricbeat/metricbeat.yml
  async: 45
  poll: 0

- name: METRICBEAT - Restart metricbeat
  service: 
     name: metricbeat 
     state: restarted
